### ISSUE TITLE
Mobile menu stays open when switching to desktop mode

### ISSUE THREAD

**Issue by jtsymon** [Arcton/arcton.github.io#19]
When you have the menu open in mobile mode and switch to desktop mode, this happens:
![image](https://cloud.githubusercontent.com/assets/4264682/18463232/940583fe-79dc-11e6-89c0-e2e73ba9c538.png)

I finally found a realistic way to reproduce this, on a tablet:
1. Hold the tablet vertically/portrait. The browser displays in mobile mode.
2. Open the menu.
3. Rotate the tablet so it is horizontal. The browser switches to desktop mode, and the website breaks.

Or on desktop (less realistic):
1. Zoom in until it switches to mobile mode
2. Open the menu
3. Zoom back out until it goes back to desktop mode, and the website breaks

This could be fixed with CSS (check the screen mode as well as whether the menu checkbox is checked), or just use Javascript to uncheck the box (which would be a horrible hack).

**Comment by GradyHooker** [comment]
Fixed in 74323f3
